# Generated by Django 2.2.1 on 2019-05-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0002_auto_20190510_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldborder',
            old_name='mpoly',
            new_name='geometry',
        ),
    ]
