# Generated by Django 2.2.1 on 2019-05-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('posts', models.ManyToManyField(blank=True, null=True, to='geoportal.Post')),
            ],
        ),
    ]
